### ISSUE TITLE
Systemd dependency

### ISSUE THREAD

**Issue by tbsteinb** [zyga/gentoo-snappy#13]
This package does not provide the files necessary for it to work without Systemd.  The readme provided steps for only systemd, but I figured it was just because it's what the developers used.  I would suggest either putting a notice in the readme specifying that it only works with systemd for the time being, or if there are no plans to support OpenRC in the future adding a systemd dependency (really that should be there regardless, and if OpenRC support is added then a systemd useflag should be added).

**Comment by BTrey** [comment]
Fix this.  Many of the people using Gentoo use it because it's one of the few systems that still doesn't require the systemd abomination.  Note that I'm not complaining about you using systemd or creating a package that depends on it.  That is absolutely your choice.  But it would take you about five seconds and a handful of ASCII to add "This overlay requires the use of systemd" to the front page.  That would have saved me the time of creating the overlay, syncing my system, installing the package and then having to turn around an undo everything I'd just done.  Alternately, if there IS a way to make this work without systemd, then please add instructions to reflect that.  But please do something to quit wasting people's time.

**Comment by zelurker** [comment]
wow not even a reply in 6 months to this !
it should be fixable for someone really wanting to do it, just convert the config files in lib/systemd/system/snap* to some script for openrc, it shouldn't be that hard for someone who knows well systemd.
Too bad, for the time being I think I'll just uninstall this then...

**Comment by tbsteinb** [comment]
zelurker, there is another issue on here similar to mine. If you look through there, you'll notice his stance on this. I'm actually going to close this issue since this is not something he can do much for. At best he can just add a systemd dependency. He also mentions that he needs help on this project (though that would be more for people with systemd).

Getting snappy to work on OpenRC is more than just converting a few OpenRC scripts. Snappy depends on some core features of systemd, so much so in fact that the last version of Ubuntu to use Upstart by default included a modified version of systemd specifically so snappy would work.

**Comment by zelurker** [comment]
ok, thanks for the info, I'll look into docker for now...

2018-03-27 7:10 GMT+02:00 tbsteinb <notifications@github.com>:
